### ISSUE TITLE
please provide exe

### ISSUE THREAD

**Issue by amigax** [KodeMunkie/imagetozxspec#2]
We aren't all C coders you know :) supply prebuilt binaries!

**Comment by KodeMunkie** [comment]
The prebuilt "binaries" are in the "Assets" section of the Releases (or just follow the link for the zip distribution from the front project page) - this is the same location on GitHub for everyones' project. I think you may also be getting confused, since this is Java there is no .exe but a executable Java Jar inside the zip download. Thanks for feedback :)

**Comment by amigax** [comment]
actually i dont see assets dir ;-)

**Comment by KodeMunkie** [comment]
It's not in the source file location/folders - it's linked from both the project front page see "zip distribution" bottom, or take the long route :) , Click Code tab -> click Releases sub tab -> Expand Assets.
Alternatively just go here: https://github.com/KodeMunkie/imagetozxspec/releases and expand the Assets as discussed. Thanks.

**Comment by amigax** [comment]
thanks, highly confusing, been using github for 10 yrs never even saw releases, I now see links in the readme. One of my hatreds of github is uncompiled shit, thanks.
