### ISSUE TITLE
How do I slow down the animation playback during conversion?

### ISSUE THREAD

**Issue by Orangery-DS** [KodeMunkie/imagetozxspec#8]
Hello - I have tried changing the 'Anim Gif  Frame Delay' setting to 2000 milliseconds but it does not seem to have any effect on the outcome.  The playback speed is always too fast (whatever the input).  Can you help with this please? 

I am using Windows 10 and versions 2.0.2 and 2.2.2 of imagetozxspec.

Thank you - Dave S.

**Comment by KodeMunkie** [comment]
The anim gif frame delay is the amount of time between frames of the animation in hundredths of a second. Depending on the playback tool you are using, it may not honour the time delay. You can verify the delay yourself by opening the anim gif in an editor like Microsoft Gif Animator and viewing the setting.

**Comment by Orangery-DS** [comment]
Thanks for the reply.

I think we may be at cross purposes here.   I am trying to slow down the
'Display Result Time (Seconds)' as shown in an earlier version on YouTube
timestamped at 4:40.  Is this version of the program still available?

**Comment by KodeMunkie** [comment]
I'd totally forgotten that tutorial video existed :D

Ok long answer, please bear with me!

The "display result time" option was only to slow down the processing within Image To ZX Spec so you could see the output image by image and potentially modify the next frame/image. The display result time does not affect the output - the time between frames is handled by the BASIC loader (as an input option when you play the slideshow) or if it's a GIF, as described in the previous comment.

On a related note, the ability to view the frame and change the settings whilst it is processing was and is a bit of a hack due to image read ahead/out of order processing (there is no guarantee your settings will apply to the frame you are looking at, the frame you expect next, or even to the entire frame) and another reason that option was removed.

I've not blocked the UI settings from being changed entirely because it is still a useful feature for testing when converting videos since you may need to see how a particular scene looks at 10 minutes into a film and don't want to have to wait 10 minutes to get to that point (as there is no skip/jump to point in video option).

The work around should you want to change the settings for various single images is to use the preview and/or output the image you want using different settings - the UI supports drag and drop making this quite easy. Regrettably this will not allow you to build a GIF with lots of images using different settings as you may be used to with an earlier version of the app.

Technically changing settings whilst processing is also both a bug (accidental changes) and feature (deliberately want to change) and therefore not one I would like to see brought back.

If I had the time and motivation I'd do away with changes during processing and implement a per frame editor which would be the ideal solution.

**Comment by Orangery-DS** [comment]
Thanks for the explanation.  Well I found the 1.05 version (that you used
in the demonstration video) via your well organised Silent Software site.

I tried it out and it worked fine.  So now I can view each image, one at a
time during conversion.

If I can put the program to good use, I'll buy you a coffee via the link.

Many thanks - Dave S.

**Comment by KodeMunkie** [comment]
What was the use case for this feature please - I note that 1.0.5 doesn't support video or anim gifs as per bug report initial post, so I'm uncertain as to what you'd like to do?

Also, you may find the earlier versions fail to run in newer versions of Java and there are a number of rendering issues (preview vs actual result had quite a few bugs early on). 
You'll also miss out on newer features like improved colour accuracy from colour distance algorithms, vast performance improvements, 102 colour support and quite a lot of bug fixes. As you might appreciate, I cannot support problems with earlier revisions that may have been fixed.

**Comment by Orangery-DS** [comment]
Version 1.0.5 is the better version for me, as I can change the 'display
result time' when converting images to ZX Spectrum format.  I won't be
using animations or video.  Performance is not an issue either .

I had a Spectrum 48K in the day, and have an interest in low resolution,
abstract images.  I may want to produce hard copies of some, once I get my
printer working again.  I need to experiment a little more with the program
first though.

**Comment by KodeMunkie** [comment]
Ah ok. I thought you had a specific use case for needing that feature (e.g. to take screenshots, and existing preview inadequate) rather than just experimenting.
Good luck!

**Comment by Orangery-DS** [comment]
I've only just realised that you can alter various parameters on the fly.
I like to set the slideshow (Display Result Time) to 2 or 5 seconds
(version 1.0.5).

I will experiment further - thank you.
